// Generated by gencpp from file evry_project_plugins/DistanceToFlagResponse.msg
// DO NOT EDIT!


#ifndef EVRY_PROJECT_PLUGINS_MESSAGE_DISTANCETOFLAGRESPONSE_H
#define EVRY_PROJECT_PLUGINS_MESSAGE_DISTANCETOFLAGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace evry_project_plugins
{
template <class ContainerAllocator>
struct DistanceToFlagResponse_
{
  typedef DistanceToFlagResponse_<ContainerAllocator> Type;

  DistanceToFlagResponse_()
    : distance(0.0)  {
    }
  DistanceToFlagResponse_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DistanceToFlagResponse_

typedef ::evry_project_plugins::DistanceToFlagResponse_<std::allocator<void> > DistanceToFlagResponse;

typedef boost::shared_ptr< ::evry_project_plugins::DistanceToFlagResponse > DistanceToFlagResponsePtr;
typedef boost::shared_ptr< ::evry_project_plugins::DistanceToFlagResponse const> DistanceToFlagResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator1> & lhs, const ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator1> & lhs, const ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace evry_project_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acff7fda0c683c872875f5c4b069f124";
  }

  static const char* value(const ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacff7fda0c683c87ULL;
  static const uint64_t static_value2 = 0x2875f5c4b069f124ULL;
};

template<class ContainerAllocator>
struct DataType< ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "evry_project_plugins/DistanceToFlagResponse";
  }

  static const char* value(const ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance\n"
;
  }

  static const char* value(const ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DistanceToFlagResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::evry_project_plugins::DistanceToFlagResponse_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVRY_PROJECT_PLUGINS_MESSAGE_DISTANCETOFLAGRESPONSE_H
