// Generated by gencpp from file evry_project_plugins/DistanceToFlag.msg
// DO NOT EDIT!


#ifndef EVRY_PROJECT_PLUGINS_MESSAGE_DISTANCETOFLAG_H
#define EVRY_PROJECT_PLUGINS_MESSAGE_DISTANCETOFLAG_H

#include <ros/service_traits.h>


#include <evry_project_plugins/DistanceToFlagRequest.h>
#include <evry_project_plugins/DistanceToFlagResponse.h>


namespace evry_project_plugins
{

struct DistanceToFlag
{

typedef DistanceToFlagRequest Request;
typedef DistanceToFlagResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DistanceToFlag
} // namespace evry_project_plugins


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::evry_project_plugins::DistanceToFlag > {
  static const char* value()
  {
    return "cd4f1364f476ebbbc1f9cba4aa416890";
  }

  static const char* value(const ::evry_project_plugins::DistanceToFlag&) { return value(); }
};

template<>
struct DataType< ::evry_project_plugins::DistanceToFlag > {
  static const char* value()
  {
    return "evry_project_plugins/DistanceToFlag";
  }

  static const char* value(const ::evry_project_plugins::DistanceToFlag&) { return value(); }
};


// service_traits::MD5Sum< ::evry_project_plugins::DistanceToFlagRequest> should match
// service_traits::MD5Sum< ::evry_project_plugins::DistanceToFlag >
template<>
struct MD5Sum< ::evry_project_plugins::DistanceToFlagRequest>
{
  static const char* value()
  {
    return MD5Sum< ::evry_project_plugins::DistanceToFlag >::value();
  }
  static const char* value(const ::evry_project_plugins::DistanceToFlagRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::evry_project_plugins::DistanceToFlagRequest> should match
// service_traits::DataType< ::evry_project_plugins::DistanceToFlag >
template<>
struct DataType< ::evry_project_plugins::DistanceToFlagRequest>
{
  static const char* value()
  {
    return DataType< ::evry_project_plugins::DistanceToFlag >::value();
  }
  static const char* value(const ::evry_project_plugins::DistanceToFlagRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::evry_project_plugins::DistanceToFlagResponse> should match
// service_traits::MD5Sum< ::evry_project_plugins::DistanceToFlag >
template<>
struct MD5Sum< ::evry_project_plugins::DistanceToFlagResponse>
{
  static const char* value()
  {
    return MD5Sum< ::evry_project_plugins::DistanceToFlag >::value();
  }
  static const char* value(const ::evry_project_plugins::DistanceToFlagResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::evry_project_plugins::DistanceToFlagResponse> should match
// service_traits::DataType< ::evry_project_plugins::DistanceToFlag >
template<>
struct DataType< ::evry_project_plugins::DistanceToFlagResponse>
{
  static const char* value()
  {
    return DataType< ::evry_project_plugins::DistanceToFlag >::value();
  }
  static const char* value(const ::evry_project_plugins::DistanceToFlagResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EVRY_PROJECT_PLUGINS_MESSAGE_DISTANCETOFLAG_H
