// Generated by gencpp from file evry_project_plugins/DistanceToFlagRequest.msg
// DO NOT EDIT!


#ifndef EVRY_PROJECT_PLUGINS_MESSAGE_DISTANCETOFLAGREQUEST_H
#define EVRY_PROJECT_PLUGINS_MESSAGE_DISTANCETOFLAGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace evry_project_plugins
{
template <class ContainerAllocator>
struct DistanceToFlagRequest_
{
  typedef DistanceToFlagRequest_<ContainerAllocator> Type;

  DistanceToFlagRequest_()
    : agent_pose()
    , id_flag(0)  {
    }
  DistanceToFlagRequest_(const ContainerAllocator& _alloc)
    : agent_pose(_alloc)
    , id_flag(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _agent_pose_type;
  _agent_pose_type agent_pose;

   typedef int64_t _id_flag_type;
  _id_flag_type id_flag;





  typedef boost::shared_ptr< ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DistanceToFlagRequest_

typedef ::evry_project_plugins::DistanceToFlagRequest_<std::allocator<void> > DistanceToFlagRequest;

typedef boost::shared_ptr< ::evry_project_plugins::DistanceToFlagRequest > DistanceToFlagRequestPtr;
typedef boost::shared_ptr< ::evry_project_plugins::DistanceToFlagRequest const> DistanceToFlagRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator1> & lhs, const ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator2> & rhs)
{
  return lhs.agent_pose == rhs.agent_pose &&
    lhs.id_flag == rhs.id_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator1> & lhs, const ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace evry_project_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a87fe30206b654a56a3d2b0174397bd3";
  }

  static const char* value(const ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa87fe30206b654a5ULL;
  static const uint64_t static_value2 = 0x6a3d2b0174397bd3ULL;
};

template<class ContainerAllocator>
struct DataType< ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "evry_project_plugins/DistanceToFlagRequest";
  }

  static const char* value(const ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D agent_pose\n"
"int64 id_flag\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.agent_pose);
      stream.next(m.id_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DistanceToFlagRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::evry_project_plugins::DistanceToFlagRequest_<ContainerAllocator>& v)
  {
    s << indent << "agent_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.agent_pose);
    s << indent << "id_flag: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVRY_PROJECT_PLUGINS_MESSAGE_DISTANCETOFLAGREQUEST_H
